INSERT INTO app.provinces (id, name, slug) VALUES (1, 'آذربايجان شرقي', 'azerbaijan-east');
INSERT INTO app.provinces (id, name, slug) VALUES (2, 'آذربايجان غربي', 'azerbaijan-west');
INSERT INTO app.provinces (id, name, slug) VALUES (3, 'اردبيل', 'ardabil');
INSERT INTO app.provinces (id, name, slug) VALUES (4, 'اصفهان', 'isfahan');
INSERT INTO app.provinces (id, name, slug) VALUES (5, 'البرز', 'alborz');
INSERT INTO app.provinces (id, name, slug) VALUES (6, 'ايلام', 'ilam');
INSERT INTO app.provinces (id, name, slug) VALUES (7, 'بوشهر', 'bushehr');
INSERT INTO app.provinces (id, name, slug) VALUES (8, 'تهران', 'tehran');
INSERT INTO app.provinces (id, name, slug) VALUES (9, 'چهارمحال بختياري', 'chahar-mahaal-bakhtiari');
INSERT INTO app.provinces (id, name, slug) VALUES (10, 'خراسان جنوبي', 'khorasan-south');
INSERT INTO app.provinces (id, name, slug) VALUES (11, 'خراسان رضوي', 'khorasan-razavi');
INSERT INTO app.provinces (id, name, slug) VALUES (12, 'خراسان شمالي', 'khorasan-north');
INSERT INTO app.provinces (id, name, slug) VALUES (13, 'خوزستان', 'khuzestan');
INSERT INTO app.provinces (id, name, slug) VALUES (14, 'زنجان', 'zanjan');
INSERT INTO app.provinces (id, name, slug) VALUES (15, 'سمنان', 'semnan');
INSERT INTO app.provinces (id, name, slug) VALUES (16, 'سيستان و بلوچستان', 'sistan-baluchestan');
INSERT INTO app.provinces (id, name, slug) VALUES (17, 'فارس', 'fars');
INSERT INTO app.provinces (id, name, slug) VALUES (18, 'قزوين', 'qazvin');
INSERT INTO app.provinces (id, name, slug) VALUES (19, 'قم', 'qom');
INSERT INTO app.provinces (id, name, slug) VALUES (20, 'كردستان', 'kurdistan');
INSERT INTO app.provinces (id, name, slug) VALUES (21, 'كرمان', 'kerman');
INSERT INTO app.provinces (id, name, slug) VALUES (22, 'كرمانشاه', 'kermanshah');
INSERT INTO app.provinces (id, name, slug) VALUES (23, 'كهكيلويه و بويراحمد', 'kohgiluyeh-boyer-ahmad');
INSERT INTO app.provinces (id, name, slug) VALUES (24, 'گلستان', 'golestan');
INSERT INTO app.provinces (id, name, slug) VALUES (25, 'گيلان', 'gilan');
INSERT INTO app.provinces (id, name, slug) VALUES (26, 'لرستان', 'lorestan');
INSERT INTO app.provinces (id, name, slug) VALUES (27, 'مازندران', 'mazandaran');
INSERT INTO app.provinces (id, name, slug) VALUES (28, 'مرکزی', 'markazi');
INSERT INTO app.provinces (id, name, slug) VALUES (29, 'هرمزگان', 'hormozgan');
INSERT INTO app.provinces (id, name, slug) VALUES (30, 'همدان', 'hamadan');
INSERT INTO app.provinces (id, name, slug) VALUES (31, 'يزد', 'yazd');
