INSERT INTO app.provinces (id, name) VALUES (1, 'آذربايجان شرقي');
INSERT INTO app.provinces (id, name) VALUES (2, 'آذربايجان غربي');
INSERT INTO app.provinces (id, name) VALUES (3, 'اردبيل');
INSERT INTO app.provinces (id, name) VALUES (4, 'اصفهان');
INSERT INTO app.provinces (id, name) VALUES (5, 'البرز');
INSERT INTO app.provinces (id, name) VALUES (6, 'ايلام');
INSERT INTO app.provinces (id, name) VALUES (7, 'بوشهر');
INSERT INTO app.provinces (id, name) VALUES (8, 'تهران');
INSERT INTO app.provinces (id, name) VALUES (9, 'چهارمحال بختياري');
INSERT INTO app.provinces (id, name) VALUES (10, 'خراسان جنوبي');
INSERT INTO app.provinces (id, name) VALUES (11, 'خراسان رضوي');
INSERT INTO app.provinces (id, name) VALUES (12, 'خراسان شمالي');
INSERT INTO app.provinces (id, name) VALUES (13, 'خوزستان');
INSERT INTO app.provinces (id, name) VALUES (14, 'زنجان');
INSERT INTO app.provinces (id, name) VALUES (15, 'سمنان');
INSERT INTO app.provinces (id, name) VALUES (16, 'سيستان و بلوچستان');
INSERT INTO app.provinces (id, name) VALUES (17, 'فارس');
INSERT INTO app.provinces (id, name) VALUES (18, 'قزوين');
INSERT INTO app.provinces (id, name) VALUES (19, 'قم');
INSERT INTO app.provinces (id, name) VALUES (20, 'كردستان');
INSERT INTO app.provinces (id, name) VALUES (21, 'كرمان');
INSERT INTO app.provinces (id, name) VALUES (22, 'كرمانشاه');
INSERT INTO app.provinces (id, name) VALUES (23, 'كهكيلويه و بويراحمد');
INSERT INTO app.provinces (id, name) VALUES (24, 'گلستان');
INSERT INTO app.provinces (id, name) VALUES (25, 'گيلان');
INSERT INTO app.provinces (id, name) VALUES (26, 'لرستان');
INSERT INTO app.provinces (id, name) VALUES (27, 'مازندران');
INSERT INTO app.provinces (id, name) VALUES (28, 'مرکزی');
INSERT INTO app.provinces (id, name) VALUES (29, 'هرمزگان');
INSERT INTO app.provinces (id, name) VALUES (30, 'همدان');
INSERT INTO app.provinces (id, name) VALUES (31, 'يزد');